services:
  ollama-container:
    image: ollama/ollama
    volumes:
      - ./ollama:/root/.ollama
      - ./run-ollama.sh:/root/run-ollama.sh
    ports:
      - 11434:11434
    entrypoint: /bin/bash -c "chmod +x /root/run-ollama.sh && /root/run-ollama.sh"
  streamlit-app:
    build: ./app
    ports:
      - 8501:8501